import "./globals.css";
import Link from "next/link";
import { neobrutalism } from "@clerk/themes";
import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";

import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
      signInForceRedirectUrl="/"
      signUpForceRedirectUrl="/"
    >
      <html lang="en">
        <body
          className={`${inter.variable} ${robotoMono.variable} antialiased`}
        >
          <header className="h-20 border-b">
            <div className="w-full h-full flex items-center justify-between px-8">
              <Link href="/" className="font-bold text-3xl">
                Clerk Setup
              </Link>
              <div className="flex items-center gap-4">
                <SignedOut>
                  <SignInButton></SignInButton>
                  <SignUpButton></SignUpButton>
                </SignedOut>
                <SignedIn>
                  <UserButton/>
                </SignedIn>
              </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}